# https://github.com/requarks/wiki-docs/blob/master/install/docker.md#using-docker-compose

version: "3"
services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: wikidb
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wikidb
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  db-data:
  
# ProxyPass / http://localhost:3000/
# ProxyPassReverse / http://localhost:3000/
